# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyAttributeOutsideInit,PyPep8
class Ui_Form(object):
    # noinspection PyPep8
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 580)
        Form.setMinimumSize(QtCore.QSize(430, 580))
        Form.setMaximumSize(QtCore.QSize(430, 580))
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 80, 451, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_14 = QtWidgets.QFrame(Form)
        self.line_14.setGeometry(QtCore.QRect(-10, 330, 461, 16))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 220, 411, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 3, 0, 1, 1)
        self.kindIMG = QtWidgets.QComboBox(self.layoutWidget)
        self.kindIMG.setMaxVisibleItems(5)
        self.kindIMG.setObjectName("kindIMG")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.kindIMG.addItem("")
        self.gridLayout_8.addWidget(self.kindIMG, 3, 1, 1, 1)
        self.contPOINTS = QtWidgets.QSpinBox(self.layoutWidget)
        self.contPOINTS.setMaximum(1000)
        self.contPOINTS.setProperty("value", 0)
        self.contPOINTS.setObjectName("contPOINTS")
        self.gridLayout_8.addWidget(self.contPOINTS, 0, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget)
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 2, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget)
        self.label_54.setObjectName("label_54")
        self.gridLayout_8.addWidget(self.label_54, 0, 0, 1, 1)
        self.checkContour = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkContour.setObjectName("checkContour")
        self.gridLayout_8.addWidget(self.checkContour, 1, 1, 1, 1)
        self.kindCONT = QtWidgets.QComboBox(self.layoutWidget)
        self.kindCONT.setObjectName("kindCONT")
        self.kindCONT.addItem("")
        self.kindCONT.addItem("")
        self.kindCONT.addItem("")
        self.kindCONT.addItem("")
        self.kindCONT.addItem("")
        self.kindCONT.addItem("")
        self.gridLayout_8.addWidget(self.kindCONT, 2, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 411, 76))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.openFILE = QtWidgets.QPushButton(self.layoutWidget1)
        self.openFILE.setObjectName("openFILE")
        self.verticalLayout.addWidget(self.openFILE)
        self.fileNAME = QtWidgets.QLineEdit(self.layoutWidget1)
        self.fileNAME.setObjectName("fileNAME")
        self.verticalLayout.addWidget(self.fileNAME)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(4, 340, 420, 231))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.en_y1 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.en_y1.setMinimum(-100000.0)
        self.en_y1.setMaximum(100000.0)
        self.en_y1.setSingleStep(0.5)
        self.en_y1.setObjectName("en_y1")
        self.gridLayout_5.addWidget(self.en_y1, 3, 2, 1, 1)
        self.en_x0 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.en_x0.setMinimum(-100000.0)
        self.en_x0.setMaximum(100000.0)
        self.en_x0.setSingleStep(0.5)
        self.en_x0.setObjectName("en_x0")
        self.gridLayout_5.addWidget(self.en_x0, 2, 1, 1, 1)
        self.enSHIFT_Y = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.enSHIFT_Y.setMinimum(-1000.0)
        self.enSHIFT_Y.setMaximum(1000.0)
        self.enSHIFT_Y.setSingleStep(0.5)
        self.enSHIFT_Y.setObjectName("enSHIFT_Y")
        self.gridLayout_5.addWidget(self.enSHIFT_Y, 5, 1, 1, 1)
        self.em_AVSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.em_AVSpinBox.setMinimum(-100.0)
        self.em_AVSpinBox.setMaximum(100.0)
        self.em_AVSpinBox.setSingleStep(0.5)
        self.em_AVSpinBox.setObjectName("em_AVSpinBox")
        self.gridLayout_5.addWidget(self.em_AVSpinBox, 4, 2, 1, 1)
        self.enSHIFT_X = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.enSHIFT_X.setMinimum(-1000.0)
        self.enSHIFT_X.setMaximum(1000.0)
        self.enSHIFT_X.setSingleStep(0.5)
        self.enSHIFT_X.setObjectName("enSHIFT_X")
        self.gridLayout_5.addWidget(self.enSHIFT_X, 4, 1, 1, 1)
        self.inc_AVSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.inc_AVSpinBox.setMinimum(-100.0)
        self.inc_AVSpinBox.setMaximum(100.0)
        self.inc_AVSpinBox.setSingleStep(0.5)
        self.inc_AVSpinBox.setObjectName("inc_AVSpinBox")
        self.gridLayout_5.addWidget(self.inc_AVSpinBox, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 5, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_43.setTextFormat(QtCore.Qt.AutoText)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 2, 1, 1)
        self.en_x1 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.en_x1.setMinimum(-100000.0)
        self.en_x1.setMaximum(100000.0)
        self.en_x1.setSingleStep(0.5)
        self.en_x1.setObjectName("en_x1")
        self.gridLayout_5.addWidget(self.en_x1, 3, 1, 1, 1)
        self.en_y0 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.en_y0.setMinimum(-100000.0)
        self.en_y0.setMaximum(100000.0)
        self.en_y0.setSingleStep(0.5)
        self.en_y0.setObjectName("en_y0")
        self.gridLayout_5.addWidget(self.en_y0, 2, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_44.setTextFormat(QtCore.Qt.AutoText)
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_45.setTextFormat(QtCore.Qt.AutoText)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 3, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_5)
        self.RIXSPlot = QtWidgets.QPushButton(self.layoutWidget2)
        self.RIXSPlot.setObjectName("RIXSPlot")
        self.verticalLayout_12.addWidget(self.RIXSPlot)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 100, 411, 115))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 2, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_47.setObjectName("label_47")
        self.gridLayout_6.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 0, 0, 1, 1)
        self.kindRIXS = QtWidgets.QComboBox(self.layoutWidget3)
        self.kindRIXS.setMaxVisibleItems(2)
        self.kindRIXS.setIconSize(QtCore.QSize(16, 16))
        self.kindRIXS.setObjectName("kindRIXS")
        self.kindRIXS.addItem("")
        self.kindRIXS.addItem("")
        self.gridLayout_6.addWidget(self.kindRIXS, 2, 1, 1, 1)
        self.gridPOINTS = QtWidgets.QSpinBox(self.layoutWidget3)
        self.gridPOINTS.setMinimum(10)
        self.gridPOINTS.setMaximum(5000)
        self.gridPOINTS.setProperty("value", 500)
        self.gridPOINTS.setObjectName("gridPOINTS")
        self.gridLayout_6.addWidget(self.gridPOINTS, 0, 1, 1, 1)
        self.kindINTER = QtWidgets.QComboBox(self.layoutWidget3)
        self.kindINTER.setMaxVisibleItems(3)
        self.kindINTER.setObjectName("kindINTER")
        self.kindINTER.addItem("")
        self.kindINTER.addItem("")
        self.kindINTER.addItem("")
        self.kindINTER.addItem("")
        self.gridLayout_6.addWidget(self.kindINTER, 1, 1, 1, 1)
        self.line_15 = QtWidgets.QFrame(Form)
        self.line_15.setGeometry(QtCore.QRect(0, 0, 431, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(Form)
        self.line_16.setGeometry(QtCore.QRect(0, 210, 451, 16))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")

        self.retranslateUi(Form)
        self.kindRIXS.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.openFILE, self.fileNAME)
        Form.setTabOrder(self.fileNAME, self.gridPOINTS)
        Form.setTabOrder(self.gridPOINTS, self.kindINTER)
        Form.setTabOrder(self.kindINTER, self.kindRIXS)
        Form.setTabOrder(self.kindRIXS, self.contPOINTS)
        Form.setTabOrder(self.contPOINTS, self.checkContour)
        Form.setTabOrder(self.checkContour, self.kindCONT)
        Form.setTabOrder(self.kindCONT, self.kindIMG)
        Form.setTabOrder(self.kindIMG, self.en_x0)
        Form.setTabOrder(self.en_x0, self.en_y0)
        Form.setTabOrder(self.en_y0, self.en_x1)
        Form.setTabOrder(self.en_x1, self.en_y1)
        Form.setTabOrder(self.en_y1, self.enSHIFT_X)
        Form.setTabOrder(self.enSHIFT_X, self.em_AVSpinBox)
        Form.setTabOrder(self.em_AVSpinBox, self.enSHIFT_Y)
        Form.setTabOrder(self.enSHIFT_Y, self.inc_AVSpinBox)
        Form.setTabOrder(self.inc_AVSpinBox, self.RIXSPlot)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "RIXS Plot"))
        self.label_52.setText(_translate("Form", "Image-Style"))
        self.kindIMG.setItemText(0, _translate("Form", "viridis"))
        self.kindIMG.setItemText(1, _translate("Form", "inferno"))
        self.kindIMG.setItemText(2, _translate("Form", "plasma"))
        self.kindIMG.setItemText(3, _translate("Form", "magma"))
        self.kindIMG.setItemText(4, _translate("Form", "Blues"))
        self.kindIMG.setItemText(5, _translate("Form", "BuGn"))
        self.kindIMG.setItemText(6, _translate("Form", "BuPu"))
        self.kindIMG.setItemText(7, _translate("Form", "GnBu"))
        self.kindIMG.setItemText(8, _translate("Form", "Greens"))
        self.kindIMG.setItemText(9, _translate("Form", "Greys"))
        self.kindIMG.setItemText(10, _translate("Form", "Oranges"))
        self.kindIMG.setItemText(11, _translate("Form", "OrRd"))
        self.kindIMG.setItemText(12, _translate("Form", "PuBu"))
        self.kindIMG.setItemText(13, _translate("Form", "PuBuGn"))
        self.kindIMG.setItemText(14, _translate("Form", "PuRd"))
        self.kindIMG.setItemText(15, _translate("Form", "Purples"))
        self.kindIMG.setItemText(16, _translate("Form", "RdPu"))
        self.kindIMG.setItemText(17, _translate("Form", "Reds"))
        self.kindIMG.setItemText(18, _translate("Form", "YlGn"))
        self.kindIMG.setItemText(19, _translate("Form", "YlGnBu"))
        self.kindIMG.setItemText(20, _translate("Form", "YlOrBr"))
        self.kindIMG.setItemText(21, _translate("Form", "YlOrRd"))
        self.kindIMG.setItemText(22, _translate("Form", "afmhot"))
        self.kindIMG.setItemText(23, _translate("Form", "autumn"))
        self.kindIMG.setItemText(24, _translate("Form", "bone"))
        self.kindIMG.setItemText(25, _translate("Form", "cool"))
        self.kindIMG.setItemText(26, _translate("Form", "cooper"))
        self.kindIMG.setItemText(27, _translate("Form", "gist_heat"))
        self.kindIMG.setItemText(28, _translate("Form", "gray"))
        self.kindIMG.setItemText(29, _translate("Form", "hot"))
        self.kindIMG.setItemText(30, _translate("Form", "pink"))
        self.kindIMG.setItemText(31, _translate("Form", "spring"))
        self.kindIMG.setItemText(32, _translate("Form", "summer"))
        self.kindIMG.setItemText(33, _translate("Form", "winter"))
        self.kindIMG.setItemText(34, _translate("Form", "BrBG"))
        self.kindIMG.setItemText(35, _translate("Form", "bwr"))
        self.kindIMG.setItemText(36, _translate("Form", "coolwarm"))
        self.kindIMG.setItemText(37, _translate("Form", "PiYG"))
        self.kindIMG.setItemText(38, _translate("Form", "PRGn"))
        self.kindIMG.setItemText(39, _translate("Form", "PuOr"))
        self.kindIMG.setItemText(40, _translate("Form", "RdBu"))
        self.kindIMG.setItemText(41, _translate("Form", "RdGy"))
        self.kindIMG.setItemText(42, _translate("Form", "RdYlBu"))
        self.kindIMG.setItemText(43, _translate("Form", "RdYlGn"))
        self.kindIMG.setItemText(44, _translate("Form", "Spectral"))
        self.kindIMG.setItemText(45, _translate("Form", "seismic"))
        self.kindIMG.setItemText(46, _translate("Form", "Accent"))
        self.kindIMG.setItemText(47, _translate("Form", "Dark2"))
        self.kindIMG.setItemText(48, _translate("Form", "Paired"))
        self.kindIMG.setItemText(49, _translate("Form", "Pastel1"))
        self.kindIMG.setItemText(50, _translate("Form", "Pastel2"))
        self.kindIMG.setItemText(51, _translate("Form", "Set1"))
        self.kindIMG.setItemText(52, _translate("Form", "Set2"))
        self.kindIMG.setItemText(53, _translate("Form", "Set3"))
        self.kindIMG.setItemText(54, _translate("Form", "gist_earth"))
        self.kindIMG.setItemText(55, _translate("Form", "terrain"))
        self.kindIMG.setItemText(56, _translate("Form", "ocean"))
        self.kindIMG.setItemText(57, _translate("Form", "gist_stern"))
        self.kindIMG.setItemText(58, _translate("Form", "brg"))
        self.kindIMG.setItemText(59, _translate("Form", "CMRmap"))
        self.kindIMG.setItemText(60, _translate("Form", "cubehelix"))
        self.kindIMG.setItemText(61, _translate("Form", "gnuplot"))
        self.kindIMG.setItemText(62, _translate("Form", "gnuplot2"))
        self.kindIMG.setItemText(63, _translate("Form", "gist_ncar"))
        self.kindIMG.setItemText(64, _translate("Form", "nipy_spectral"))
        self.kindIMG.setItemText(65, _translate("Form", "jet"))
        self.kindIMG.setItemText(66, _translate("Form", "rainbow"))
        self.kindIMG.setItemText(67, _translate("Form", "gist_rainbow"))
        self.kindIMG.setItemText(68, _translate("Form", "hsv"))
        self.kindIMG.setItemText(69, _translate("Form", "flag"))
        self.kindIMG.setItemText(70, _translate("Form", "prism"))
        self.label_53.setText(_translate("Form", "Contour-Style"))
        self.label_54.setText(_translate("Form", "Contours"))
        self.checkContour.setText(_translate("Form", "Only Contours"))
        self.kindCONT.setItemText(0, _translate("Form", "Linear"))
        self.kindCONT.setItemText(1, _translate("Form", "Log"))
        self.kindCONT.setItemText(2, _translate("Form", "Sqrt"))
        self.kindCONT.setItemText(3, _translate("Form", "Power"))
        self.kindCONT.setItemText(4, _translate("Form", "Exp"))
        self.kindCONT.setItemText(5, _translate("Form", "Arccosh"))
        self.openFILE.setText(_translate("Form", "Open"))
        self.fileNAME.setText(_translate("Form", "out"))
        self.label.setText(_translate("Form", "Average"))
        self.label_43.setText(_translate("Form", "Energy-Shift"))
        self.label_2.setText(_translate("Form", "Incident (x)"))
        self.label_3.setText(_translate("Form", "Emission (y)"))
        self.label_44.setText(_translate("Form", "Start"))
        self.label_45.setText(_translate("Form", "End"))
        self.RIXSPlot.setText(_translate("Form", "Plot"))
        self.label_46.setText(_translate("Form", "RIXS-Mode"))
        self.label_47.setText(_translate("Form", "Interpolation"))
        self.label_49.setText(_translate("Form", "Gridpoints"))
        self.kindRIXS.setItemText(0, _translate("Form", "Emission"))
        self.kindRIXS.setItemText(1, _translate("Form", "Energy Loss"))
        self.kindINTER.setItemText(0, _translate("Form", "Linear"))
        self.kindINTER.setItemText(1, _translate("Form", "Nearest-Neighbor"))
        self.kindINTER.setItemText(2, _translate("Form", "Cubic"))
        self.kindINTER.setItemText(3, _translate("Form", "Gaussian"))
